= A

[[a_an]]
== a; an

Before an acronym, let pronunciation be your guide: 

* [green]#an SHT# (ess-aytch-tee), not [red]#a SHT#; [green]#a CCW# (see-see-double-yoo), not [red]#an CCW#. 
* Before a silent *h* use 'an' ([green]#it's an honest mistake#) but where the *h* is pronounced use 'a' ([green]#we found a heretic#).

[[abbreviations]]
== abbreviations

Use abbreviations with care.
Don't take it for granted that all readers are familiar with an abbreviation.

* *Do* give the full expansion the first time you use the term in a topic.
If you will use the abbreviation of the term later in the topic, then first put it in brackets immediately after the full expansion.
[green]#A super-heavy tank (SHT) is a fearsome machine. It's common for several SHTs to work together...#
* *Don't* use an unfamiliar abbreviation if it won't be used again in the text.
* *Don't* use an abbreviation as a verb ([green]#Use SHWs against prime targets#, not [red]#SHW prime targets#).
* *Don't* include full stops in abbreviations.
* *Don't* use an apostrophe to pluralise abbreviations unless the abbreviation ends in an *s* ([green]#the titan destroyed two SHTs#; [green]#_Epic 40,000_ was published in the late 1990s#). 
 
== acronyms and initialisms

See also <<abbreviations>>.

We define an *acronym* as a set of initial letters of words, which we then pronounce as a word ([green]#PIN#; [green]#NASA#).

We define an *initialism* as a set of initial letters of words, which we *do not* pronounce as a word ([green]#SHT#; [green]#GW#).

In general, you should use upper case for both acronyms and initialisms.
But note the common exceptions:

* Where an acronym is used as a proper name then you may capitalise just the first letter, to avoid an excess of capital letters ([green]#Nasa#).
But in general, aim to follow whatever convention the organisation itself uses. 
* Some words that started out as acronyms are now treated as orthodox nouns (as with [green]#laser#). 

TIP: Take extra care with *a* and *an* before an acronym or initialism (see <<a_an>>).

== admonitions; notices

Asciidoc includes five built-in admonition types: `NOTE`; `TIP`; `IMPORTANT`; `CAUTION`; `WARNING`.

* We define our usage in this project at xref:core:ROOT:how-to-use-this-publication.adoc[].
* Learn about the markup at link:https://docs.antora.org/antora/latest/asciidoc/admonitions/[Admonitions^].

We also use custom admonitions, based on the built-in types.
You can only use these with the block markup -- you can't use them with the inline markup.

[NOTE]
.Workaround for PDF outputs
=====
Custom admonitions work well in HTML output, but PDF output just renders the base type -- and it is not easy to customise the PDF output in this respect.
As a workaround until we can find a better approach, be sure to (a) add a title label to each custom admonition, and (b) preface the title text with the appropriate word and a colon, like this:

[,asciidoc]
----
[NOTE.option]
.Option: Title of this 'option' admonition
====
Body text of this 'option' admonition.
====
----

=====

* For notes about differences from {e40k}, don't use admonitions -- rather, use footnotes in the form `+footnote:[{e40k-diff}]+`.

== ALPHA; BETA

When you mean to refer to an early product release in prose, use upper case.
[green]#This is an ALPHA release#.
Don't use [red]#This is in ALPHA#.

== and/or

Do not place spaces around the forward slash.
 
== anthropomorphism (humanising inanimate objects)

Use your judgement here.
Words like *allows*, *needs*, *offers* and *permits* are anthropomorphic, but generally acceptable.
See link:http://john.maloney.org/Editing/anthropomorphization.htm[Anthropomorphism^].

Also, choose your words such that you don't conflate things that the player does or that happen as game effects with things that happen 'in universe'.
 
== apostrophes

* Use the normal possessive ending ([green]#'s#) after singular words or names that end in *s* ([green]#Warboss's retinue#; [green]#Saint Scythus's fame#), and after plurals that do not end in *s* ([green]#Gretchin's#; [green]#Eldar's#; [green]#Guardsmen's#). 
* Use the ending [green]#s'# on plurals that end in *s* ([green]#the Orks' warlike nature#; [green]#the Warbosses' armies converged#. 
* Do not insert apostrophes into decades or centuries ([green]#the 1990s#; [green]#the 2000s#).

== asides

Asciidoc includes 'sidebar' markup that is suitable to hold content that is an 'aside' from the main content.

* We define our usage in this project at xref:core:ROOT:how-to-use-this-publication.adoc[].
Sometimes an aside is a better fit than an admonition.
Either way, don't overdo it.
* Learn about the markup at link:https://docs.antora.org/antora/2.3/asciidoc/sidebar/[Sidebars^].